POST http://127.0.0.1:5000/contact
Content-type: application/json

{
"firstname": "Anna",
"lastname": "Andersson",
"email": "anna.andersson@gmail.com",
"personalnumber": "550713-1405",
"address": "Utvecklargatan 12",
"zipCode": "111 22",
"city": "Stockholm",
"country": "Sweden"
}

###